/**
 * ModuleKeys TypeScript 生成器
 * ModuleKeys TypeScript Generator
 * 
 * 从 ModuleKeys.sol 合约自动生成前端的 moduleKeys.ts 文件
 * Automatically generate frontend moduleKeys.ts file from ModuleKeys.sol contract
 */

import * as fs from 'fs';
import * as path from 'path';
import { ethers } from 'ethers';

interface ModuleKeyEntry {
  key: string;
  label: string; // the string inside keccak256("...")
}
type ModuleKeyMapping = Record<string, string>;

/**
 * 生成 TypeScript 模块键文件
 */
export async function generateModuleKeysTS(): Promise<void> {
  console.log('🚀 开始生成 ModuleKeys TypeScript 文件...');
  
  try {
    // 1) 解析 Solidity 源码，提取 bytes32 constant KEY_* = keccak256("...") 定义
    const moduleKeysSolPath = path.join(__dirname, '../../src/constants/ModuleKeys.sol');
    const source = fs.readFileSync(moduleKeysSolPath, 'utf8');
    const regex = /bytes32\s+constant\s+(KEY_[A-Z0-9_]+)\s*=\s*keccak256\("([^"]+)"\)/g;
    const entries: ModuleKeyEntry[] = [];
    let match: RegExpExecArray | null;
    while ((match = regex.exec(source)) !== null) {
      entries.push({ key: match[1], label: match[2] });
    }

    if (entries.length === 0) {
      throw new Error('未能在 ModuleKeys.sol 中解析到任何 KEY_* 定义，请检查正则或源码格式。');
    }

    // 保持源码顺序
    const keyStrings = entries.map((e) => e.key);

    // 生成哈希值映射（与 Solidity 保持一致：keccak256(label)）
    const moduleKeyMapping: ModuleKeyMapping = {};
    for (const { key, label } of entries) {
      moduleKeyMapping[key] = ethers.keccak256(ethers.toUtf8Bytes(label));
    }

    // 生成 TypeScript 文件内容
    const tsContent = generateTypeScriptContent(moduleKeyMapping, keyStrings);
    
    // 确保输出目录存在
    const outputDir = path.join(__dirname, '../../frontend-config');
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }
    
    // 写入文件
    const outputPath = path.join(outputDir, 'moduleKeys.ts');
    fs.writeFileSync(outputPath, tsContent, 'utf8');
    
    console.log(`✅ ModuleKeys TypeScript 文件已生成: ${outputPath}`);
    console.log(`📊 总共生成了 ${keyStrings.length} 个模块键`);
    
    // 生成验证文件
    generateValidationFile(moduleKeyMapping, keyStrings);
    
  } catch (error) {
    console.error('❌ 生成 ModuleKeys TypeScript 文件时出错:', error);
    throw error;
  }
}

/**
 * 生成 TypeScript 文件内容
 */
function generateTypeScriptContent(
  moduleKeyMapping: ModuleKeyMapping,
  keyStrings: string[]
): string {
  const header = `/**
 * ModuleKeys - 模块键常量库
 * ModuleKeys - Module Key Constants Library
 * 
 * 此文件由 scripts/utils/generateModuleKeys.ts 自动生成
 * This file is automatically generated by scripts/utils/generateModuleKeys.ts
 * 
 * 请勿手动修改，如需更新请运行: npm run generate:module-keys
 * Do not modify manually, run: npm run generate:module-keys to update
 * 
 * 生成时间: ${new Date().toISOString()}
 * Generated at: ${new Date().toISOString()}
 */

import { ethers } from 'ethers';

/**
 * 模块键常量映射
 * Module key constants mapping
 */
export const ModuleKeys = {
`;

  const footer = `};

/**
 * 模块键字符串数组
 * Module key strings array
 */
export const MODULE_KEY_STRINGS = [
${keyStrings.map(key => `  '${key}'`).join(',\n')}
] as const;

/**
 * 模块键类型
 * Module key type
 */
export type ModuleKey = typeof MODULE_KEY_STRINGS[number];

/**
 * 验证模块键是否有效
 * Validate if module key is valid
 * @param key 模块键 / Module key
 * @returns 是否有效 / Is valid
 */
export function isValidModuleKey(key: string): key is ModuleKey {
  return MODULE_KEY_STRINGS.includes(key as ModuleKey);
}

/**
 * 获取模块键的哈希值
 * Get hash value of module key
 * @param key 模块键 / Module key
 * @returns 哈希值 / Hash value
 */
export function getModuleKeyHash(key: ModuleKey): string {
  return ModuleKeys[key];
}

/**
 * 从哈希值获取模块键
 * Get module key from hash value
 * @param hash 哈希值 / Hash value
 * @returns 模块键或 null / Module key or null
 */
export function getModuleKeyFromHash(hash: string): ModuleKey | null {
  for (const [key, value] of Object.entries(ModuleKeys)) {
    if (value === hash) {
      return key as ModuleKey;
    }
  }
  return null;
}

/**
 * 获取所有模块键
 * Get all module keys
 * @returns 所有模块键数组 / All module keys array
 */
export function getAllModuleKeys(): ModuleKey[] {
  return [...MODULE_KEY_STRINGS];
}

/**
 * 获取模块键总数
 * Get total number of module keys
 * @returns 模块键总数 / Total number of module keys
 */
export function getModuleKeyCount(): number {
  return MODULE_KEY_STRINGS.length;
}

export default ModuleKeys;
`;

  // 生成主体内容
  const body = Object.entries(moduleKeyMapping)
    .map(([key, hash]) => `  ${key}: '${hash}',`)
    .join('\n\n');

  return header + body + '\n' + footer;
}

/**
 * 生成验证文件
 */
function generateValidationFile(moduleKeyMapping: ModuleKeyMapping, keyStrings: string[]): void {
  const validationContent = `/**
 * ModuleKeys 验证文件
 * ModuleKeys Validation File
 * 
 * 用于验证生成的模块键与合约中的值是否一致
 * Used to validate that generated module keys match values in contract
 */

import { ModuleKeys } from './moduleKeys';

// 验证所有模块键的哈希值是否正确
export function validateModuleKeys(): boolean {
  const expectedHashes = {
${Object.entries(moduleKeyMapping)
    .map(([key, hash]) => `    '${key}': '${hash}'`)
    .join(',\n')}
  };

  for (const [key, expectedHash] of Object.entries(expectedHashes)) {
    const actualHash = ModuleKeys[key as keyof typeof ModuleKeys];
    if (actualHash !== expectedHash) {
      console.error(\`❌ 模块键 \${key} 哈希值不匹配:\`);
      console.error(\`   期望: \${expectedHash}\`);
      console.error(\`   实际: \${actualHash}\`);
      return false;
    }
  }

  console.log('✅ 所有模块键验证通过');
  return true;
}

// 如果直接运行此文件，执行验证
if (require.main === module) {
  validateModuleKeys();
}
`;

  const outputDir = path.join(__dirname, '../../frontend-config');
  const validationPath = path.join(outputDir, 'moduleKeysValidation.ts');
  fs.writeFileSync(validationPath, validationContent, 'utf8');
  
  console.log(`✅ ModuleKeys 验证文件已生成: ${validationPath}`);
}

/**
 * 主函数
 */
async function main() {
  await generateModuleKeysTS();
}

// 如果直接运行此文件，执行主函数
if (require.main === module) {
  main().catch(console.error);
} 