/**
 * Contract error artifact generated from contracts/scripts/generateContractErrors.ts
 * Generated at: 2026-04-17T13:21:49.247Z
 *
 * 此文件是前后端共享的 custom error selector -> 语义映射单一产物。
 * 不要在消费仓再手写第二份 selector 表。
 */

export const CONTRACT_ERROR_DEFINITIONS = [
  {
    name: 'ZeroAddress',
    signature: 'ZeroAddress()',
    fragment: 'error ZeroAddress()',
    selector: '0xd92e233d',
    message: '地址不能为零。通常表示参数缺失、地址未配置，或 Registry 未正确绑定。',
    category: 'config',
    source: 'StandardErrors',
  },
  {
    name: 'NotAContract',
    signature: 'NotAContract(address addr)',
    fragment: 'error NotAContract(address addr)',
    selector: '0x07183e3c',
    message: '目标地址不是合约，通常表示 Registry 绑定了错误地址或部署产物漂移。',
    category: 'config',
    source: 'StandardErrors',
  },
  {
    name: 'AmountIsZero',
    signature: 'AmountIsZero()',
    fragment: 'error AmountIsZero()',
    selector: '0x43ad20fc',
    message: '金额不能为零。调用方应先完成本地 preflight，再发起交易。',
    category: 'validation',
    source: 'StandardErrors',
  },
  {
    name: 'AssetNotAllowed',
    signature: 'AssetNotAllowed()',
    fragment: 'error AssetNotAllowed()',
    selector: '0x48472343',
    message: '当前资产未被协议允许，通常意味着白名单、产品线或部署配置未就绪。',
    category: 'validation',
    source: 'StandardErrors',
  },
  {
    name: 'InvalidCaller',
    signature: 'InvalidCaller()',
    fragment: 'error InvalidCaller()',
    selector: '0x48f5c3ed',
    message: '调用方或调用参数不符合当前路径要求。AICredits 购买场景下也可能代表重复 clientOrderId、未配置价格或支付金额不精确。',
    category: 'validation',
    source: 'StandardErrors',
  },
  {
    name: 'ArrayLengthMismatch',
    signature: 'ArrayLengthMismatch(uint256 length1, uint256 length2)',
    fragment: 'error ArrayLengthMismatch(uint256 length1, uint256 length2)',
    selector: '0x0d8a86a6',
    message: '数组长度不匹配。前端应先校验 tuple / 签名数组长度，再上链。',
    category: 'validation',
    source: 'StandardErrors',
  },
  {
    name: 'SettlementIntentLib__AlreadyMatched',
    signature: 'SettlementIntentLib__AlreadyMatched()',
    fragment: 'error SettlementIntentLib__AlreadyMatched()',
    selector: '0x50042902',
    message: '意图已被撮合或 reserve 已被消费，属于并发业务冲突，不建议自动重试。',
    category: 'intent',
    source: 'SettlementIntentLib',
  },
  {
    name: 'SettlementIntentLib__IntentExpired',
    signature: 'SettlementIntentLib__IntentExpired()',
    fragment: 'error SettlementIntentLib__IntentExpired()',
    selector: '0xceb96a30',
    message: '意图已过期。注意 expireAt 在本协议语义里是 expireBlock，而不是 unix timestamp。',
    category: 'intent',
    source: 'SettlementIntentLib',
  },
  {
    name: 'SettlementIntentLib__InvalidSignature',
    signature: 'SettlementIntentLib__InvalidSignature()',
    fragment: 'error SettlementIntentLib__InvalidSignature()',
    selector: '0x2d077363',
    message: '签名无效，可能是签名人、参数、链 ID、verifyingContract 或 domain 不一致。',
    category: 'intent',
    source: 'SettlementIntentLib',
  },
  {
    name: 'VaultBusinessLogic__InvalidLendIntentHash',
    signature: 'VaultBusinessLogic__InvalidLendIntentHash()',
    fragment: 'error VaultBusinessLogic__InvalidLendIntentHash()',
    selector: '0x40533466',
    message: 'lend intent hash 无效，通常表示 reserve 或取消 reserve 的参数构造有误。',
    category: 'intent',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__CallerNotLenderSigner',
    signature: 'VaultBusinessLogic__CallerNotLenderSigner()',
    fragment: 'error VaultBusinessLogic__CallerNotLenderSigner()',
    selector: '0xd2b52a69',
    message: '调用者不是 lenderSigner，本次 reserve 锁仓不允许第三方代替发起。',
    category: 'permission',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__LendIntentAlreadyMatched',
    signature: 'VaultBusinessLogic__LendIntentAlreadyMatched()',
    fragment: 'error VaultBusinessLogic__LendIntentAlreadyMatched()',
    selector: '0xdd167644',
    message: 'lend intent 已被使用，不应重复 reserve 或复用旧签名。',
    category: 'intent',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__AssetMismatch',
    signature: 'VaultBusinessLogic__AssetMismatch(address expected, address got)',
    fragment: 'error VaultBusinessLogic__AssetMismatch(address expected, address got)',
    selector: '0xf2775488',
    message: '撮合过程中 reserve 资产与借款资产不一致，通常表示前端或报价层把不同资产的意图混在一起。',
    category: 'validation',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__InsufficientReservedSum',
    signature: 'VaultBusinessLogic__InsufficientReservedSum(uint256 totalReserved, uint256 requiredBorrow)',
    fragment: 'error VaultBusinessLogic__InsufficientReservedSum(uint256 totalReserved, uint256 requiredBorrow)',
    selector: '0x45bbee8a',
    message: 'reserve 总额不足以支撑当前借款金额。应提示补 reserve 或调整报价。',
    category: 'validation',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__InsufficientCollateral',
    signature: 'VaultBusinessLogic__InsufficientCollateral(uint256 current, uint256 required)',
    fragment: 'error VaultBusinessLogic__InsufficientCollateral(uint256 current, uint256 required)',
    selector: '0x3ffde9ad',
    message: '借款人当前抵押不足。正确处理是先引导补抵押，而不是盲目重试撮合。',
    category: 'validation',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__BlocksOnlyTermOutOfRange',
    signature: 'VaultBusinessLogic__BlocksOnlyTermOutOfRange(uint256 requested, uint256 minAllowed, uint256 maxAllowed)',
    fragment: 'error VaultBusinessLogic__BlocksOnlyTermOutOfRange(uint256 requested, uint256 minAllowed, uint256 maxAllowed)',
    selector: '0xc4f6c9e6',
    message: 'blocks-only 借款期限不在 lender 允许范围内。',
    category: 'blocks-only',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'VaultBusinessLogic__BlocksOnlyRateTooLow',
    signature: 'VaultBusinessLogic__BlocksOnlyRateTooLow(uint256 requested, uint256 minRequired)',
    fragment: 'error VaultBusinessLogic__BlocksOnlyRateTooLow(uint256 requested, uint256 minRequired)',
    selector: '0xaaf1c573',
    message: 'blocks-only 利率低于 lender 最低要求。',
    category: 'blocks-only',
    source: 'VaultBusinessLogic',
  },
  {
    name: 'SettlementManager__OnlyVaultCore',
    signature: 'SettlementManager__OnlyVaultCore()',
    fragment: 'error SettlementManager__OnlyVaultCore()',
    selector: '0x4bfaf454',
    message: '当前路径只能由 VaultCore 调用。普通用户或 SDK 直接调 repayAndSettle 属于错误接入。',
    category: 'permission',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__InvalidOrderId',
    signature: 'SettlementManager__InvalidOrderId()',
    fragment: 'error SettlementManager__InvalidOrderId()',
    selector: '0xb18567bd',
    message: 'orderId 无效或无法在 ORDER_ENGINE 中解析。',
    category: 'settlement',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__NotLiquidatable',
    signature: 'SettlementManager__NotLiquidatable()',
    fragment: 'error SettlementManager__NotLiquidatable()',
    selector: '0xdac66f88',
    message: '当前订单还不满足结算/清算条件。keeper 应等待到期或新的风险信号。',
    category: 'settlement',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__BorrowerCannotSelfLiquidate',
    signature: 'SettlementManager__BorrowerCannotSelfLiquidate()',
    fragment: 'error SettlementManager__BorrowerCannotSelfLiquidate()',
    selector: '0x6a4e8f8a',
    message: 'borrower 不能把 keeper 清算入口当普通用户入口调用。',
    category: 'permission',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__NoCollateral',
    signature: 'SettlementManager__NoCollateral()',
    fragment: 'error SettlementManager__NoCollateral()',
    selector: '0x66e24701',
    message: '清算路径没有找到可处理的抵押品。通常需要联查价格、抵押余额和风控读面。',
    category: 'settlement',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__OrderMismatch',
    signature: 'SettlementManager__OrderMismatch()',
    fragment: 'error SettlementManager__OrderMismatch()',
    selector: '0xe96a3c5b',
    message: 'orderId 与 user / debtAsset 不匹配。',
    category: 'settlement',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__DebtNotCleared',
    signature: 'SettlementManager__DebtNotCleared()',
    fragment: 'error SettlementManager__DebtNotCleared()',
    selector: '0x6df1bfca',
    message: '严格全额还款释放模式下，债务尚未完全清空。',
    category: 'settlement',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__RepayPullMismatch',
    signature: 'SettlementManager__RepayPullMismatch()',
    fragment: 'error SettlementManager__RepayPullMismatch()',
    selector: '0x02288c66',
    message: 'SettlementManager 转发的还款金额与 ORDER_ENGINE 实际消耗不一致。',
    category: 'runtime',
    source: 'SettlementManager',
  },
  {
    name: 'SettlementManager__InvalidImplementation',
    signature: 'SettlementManager__InvalidImplementation()',
    fragment: 'error SettlementManager__InvalidImplementation()',
    selector: '0x259df050',
    message: '升级目标实现地址无效或没有合约代码。',
    category: 'config',
    source: 'SettlementManager',
  },
  {
    name: 'BlocksOnlyCoordinator__OnlyVaultBusinessLogic',
    signature: 'BlocksOnlyCoordinator__OnlyVaultBusinessLogic()',
    fragment: 'error BlocksOnlyCoordinator__OnlyVaultBusinessLogic()',
    selector: '0x34399ce0',
    message: '当前 blocks-only 写路径只能由 VaultBusinessLogic 进入。',
    category: 'permission',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__OnlyBorrower',
    signature: 'BlocksOnlyCoordinator__OnlyBorrower()',
    fragment: 'error BlocksOnlyCoordinator__OnlyBorrower()',
    selector: '0xf8190fbb',
    message: 'repayBlocks 只能由订单 borrower 自己调用。',
    category: 'permission',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__InvalidOrderId',
    signature: 'BlocksOnlyCoordinator__InvalidOrderId(uint256 orderId)',
    fragment: 'error BlocksOnlyCoordinator__InvalidOrderId(uint256 orderId)',
    selector: '0x5545768f',
    message: 'blocks-only orderId 不存在或超出已创建范围。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__OrderNotActive',
    signature: 'BlocksOnlyCoordinator__OrderNotActive(uint256 orderId, uint8 status)',
    fragment: 'error BlocksOnlyCoordinator__OrderNotActive(uint256 orderId, uint8 status)',
    selector: '0xbfa24650',
    message: 'blocks-only 订单不是 ACTIVE 状态，不能继续执行当前动作。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__InvalidTermBlocks',
    signature: 'BlocksOnlyCoordinator__InvalidTermBlocks(uint256 termBlocks)',
    fragment: 'error BlocksOnlyCoordinator__InvalidTermBlocks(uint256 termBlocks)',
    selector: '0xa306ce98',
    message: 'blocks-only 当前产品配置不接受该 termBlocks。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__InvalidRateBps',
    signature: 'BlocksOnlyCoordinator__InvalidRateBps(uint256 rateBps)',
    fragment: 'error BlocksOnlyCoordinator__InvalidRateBps(uint256 rateBps)',
    selector: '0x2da6023a',
    message: 'blocks-only 当前产品配置不接受该 rateBps。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__InvalidLender',
    signature: 'BlocksOnlyCoordinator__InvalidLender(address expected, address actual)',
    fragment: 'error BlocksOnlyCoordinator__InvalidLender(address expected, address actual)',
    selector: '0x01c9c4c0',
    message: 'blocks-only lender 不是 Registry 中登记的 LenderPoolVault。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__NotMatured',
    signature: 'BlocksOnlyCoordinator__NotMatured(uint256 orderId, uint256 maturityBlock, uint256 currentBlock)',
    fragment: 'error BlocksOnlyCoordinator__NotMatured(uint256 orderId, uint256 maturityBlock, uint256 currentBlock)',
    selector: '0xed7e74c1',
    message: 'blocks-only 订单尚未达到 maturityBlock，不能提前执行到期处理。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
  {
    name: 'BlocksOnlyCoordinator__NoCollateral',
    signature: 'BlocksOnlyCoordinator__NoCollateral(address borrower)',
    fragment: 'error BlocksOnlyCoordinator__NoCollateral(address borrower)',
    selector: '0xcf7afaff',
    message: 'blocks-only 绑定抵押没有被 coordinator 正常托管，或托管余额已被破坏。',
    category: 'blocks-only',
    source: 'BlocksOnlyCoordinator',
  },
] as const;

export const CONTRACT_ERROR_FRAGMENTS = [
  'error ZeroAddress()',
  'error NotAContract(address addr)',
  'error AmountIsZero()',
  'error AssetNotAllowed()',
  'error InvalidCaller()',
  'error ArrayLengthMismatch(uint256 length1, uint256 length2)',
  'error SettlementIntentLib__AlreadyMatched()',
  'error SettlementIntentLib__IntentExpired()',
  'error SettlementIntentLib__InvalidSignature()',
  'error VaultBusinessLogic__InvalidLendIntentHash()',
  'error VaultBusinessLogic__CallerNotLenderSigner()',
  'error VaultBusinessLogic__LendIntentAlreadyMatched()',
  'error VaultBusinessLogic__AssetMismatch(address expected, address got)',
  'error VaultBusinessLogic__InsufficientReservedSum(uint256 totalReserved, uint256 requiredBorrow)',
  'error VaultBusinessLogic__InsufficientCollateral(uint256 current, uint256 required)',
  'error VaultBusinessLogic__BlocksOnlyTermOutOfRange(uint256 requested, uint256 minAllowed, uint256 maxAllowed)',
  'error VaultBusinessLogic__BlocksOnlyRateTooLow(uint256 requested, uint256 minRequired)',
  'error SettlementManager__OnlyVaultCore()',
  'error SettlementManager__InvalidOrderId()',
  'error SettlementManager__NotLiquidatable()',
  'error SettlementManager__BorrowerCannotSelfLiquidate()',
  'error SettlementManager__NoCollateral()',
  'error SettlementManager__OrderMismatch()',
  'error SettlementManager__DebtNotCleared()',
  'error SettlementManager__RepayPullMismatch()',
  'error SettlementManager__InvalidImplementation()',
  'error BlocksOnlyCoordinator__OnlyVaultBusinessLogic()',
  'error BlocksOnlyCoordinator__OnlyBorrower()',
  'error BlocksOnlyCoordinator__InvalidOrderId(uint256 orderId)',
  'error BlocksOnlyCoordinator__OrderNotActive(uint256 orderId, uint8 status)',
  'error BlocksOnlyCoordinator__InvalidTermBlocks(uint256 termBlocks)',
  'error BlocksOnlyCoordinator__InvalidRateBps(uint256 rateBps)',
  'error BlocksOnlyCoordinator__InvalidLender(address expected, address actual)',
  'error BlocksOnlyCoordinator__NotMatured(uint256 orderId, uint256 maturityBlock, uint256 currentBlock)',
  'error BlocksOnlyCoordinator__NoCollateral(address borrower)',
] as const;

export const CONTRACT_ERROR_MESSAGES = {
  ZeroAddress: '地址不能为零。通常表示参数缺失、地址未配置，或 Registry 未正确绑定。',
  NotAContract: '目标地址不是合约，通常表示 Registry 绑定了错误地址或部署产物漂移。',
  AmountIsZero: '金额不能为零。调用方应先完成本地 preflight，再发起交易。',
  AssetNotAllowed: '当前资产未被协议允许，通常意味着白名单、产品线或部署配置未就绪。',
  InvalidCaller: '调用方或调用参数不符合当前路径要求。AICredits 购买场景下也可能代表重复 clientOrderId、未配置价格或支付金额不精确。',
  ArrayLengthMismatch: '数组长度不匹配。前端应先校验 tuple / 签名数组长度，再上链。',
  SettlementIntentLib__AlreadyMatched: '意图已被撮合或 reserve 已被消费，属于并发业务冲突，不建议自动重试。',
  SettlementIntentLib__IntentExpired: '意图已过期。注意 expireAt 在本协议语义里是 expireBlock，而不是 unix timestamp。',
  SettlementIntentLib__InvalidSignature: '签名无效，可能是签名人、参数、链 ID、verifyingContract 或 domain 不一致。',
  VaultBusinessLogic__InvalidLendIntentHash: 'lend intent hash 无效，通常表示 reserve 或取消 reserve 的参数构造有误。',
  VaultBusinessLogic__CallerNotLenderSigner: '调用者不是 lenderSigner，本次 reserve 锁仓不允许第三方代替发起。',
  VaultBusinessLogic__LendIntentAlreadyMatched: 'lend intent 已被使用，不应重复 reserve 或复用旧签名。',
  VaultBusinessLogic__AssetMismatch: '撮合过程中 reserve 资产与借款资产不一致，通常表示前端或报价层把不同资产的意图混在一起。',
  VaultBusinessLogic__InsufficientReservedSum: 'reserve 总额不足以支撑当前借款金额。应提示补 reserve 或调整报价。',
  VaultBusinessLogic__InsufficientCollateral: '借款人当前抵押不足。正确处理是先引导补抵押，而不是盲目重试撮合。',
  VaultBusinessLogic__BlocksOnlyTermOutOfRange: 'blocks-only 借款期限不在 lender 允许范围内。',
  VaultBusinessLogic__BlocksOnlyRateTooLow: 'blocks-only 利率低于 lender 最低要求。',
  SettlementManager__OnlyVaultCore: '当前路径只能由 VaultCore 调用。普通用户或 SDK 直接调 repayAndSettle 属于错误接入。',
  SettlementManager__InvalidOrderId: 'orderId 无效或无法在 ORDER_ENGINE 中解析。',
  SettlementManager__NotLiquidatable: '当前订单还不满足结算/清算条件。keeper 应等待到期或新的风险信号。',
  SettlementManager__BorrowerCannotSelfLiquidate: 'borrower 不能把 keeper 清算入口当普通用户入口调用。',
  SettlementManager__NoCollateral: '清算路径没有找到可处理的抵押品。通常需要联查价格、抵押余额和风控读面。',
  SettlementManager__OrderMismatch: 'orderId 与 user / debtAsset 不匹配。',
  SettlementManager__DebtNotCleared: '严格全额还款释放模式下，债务尚未完全清空。',
  SettlementManager__RepayPullMismatch: 'SettlementManager 转发的还款金额与 ORDER_ENGINE 实际消耗不一致。',
  SettlementManager__InvalidImplementation: '升级目标实现地址无效或没有合约代码。',
  BlocksOnlyCoordinator__OnlyVaultBusinessLogic: '当前 blocks-only 写路径只能由 VaultBusinessLogic 进入。',
  BlocksOnlyCoordinator__OnlyBorrower: 'repayBlocks 只能由订单 borrower 自己调用。',
  BlocksOnlyCoordinator__InvalidOrderId: 'blocks-only orderId 不存在或超出已创建范围。',
  BlocksOnlyCoordinator__OrderNotActive: 'blocks-only 订单不是 ACTIVE 状态，不能继续执行当前动作。',
  BlocksOnlyCoordinator__InvalidTermBlocks: 'blocks-only 当前产品配置不接受该 termBlocks。',
  BlocksOnlyCoordinator__InvalidRateBps: 'blocks-only 当前产品配置不接受该 rateBps。',
  BlocksOnlyCoordinator__InvalidLender: 'blocks-only lender 不是 Registry 中登记的 LenderPoolVault。',
  BlocksOnlyCoordinator__NotMatured: 'blocks-only 订单尚未达到 maturityBlock，不能提前执行到期处理。',
  BlocksOnlyCoordinator__NoCollateral: 'blocks-only 绑定抵押没有被 coordinator 正常托管，或托管余额已被破坏。',
} as const;

export const CONTRACT_ERROR_SELECTORS = {
  ZeroAddress: '0xd92e233d',
  NotAContract: '0x07183e3c',
  AmountIsZero: '0x43ad20fc',
  AssetNotAllowed: '0x48472343',
  InvalidCaller: '0x48f5c3ed',
  ArrayLengthMismatch: '0x0d8a86a6',
  SettlementIntentLib__AlreadyMatched: '0x50042902',
  SettlementIntentLib__IntentExpired: '0xceb96a30',
  SettlementIntentLib__InvalidSignature: '0x2d077363',
  VaultBusinessLogic__InvalidLendIntentHash: '0x40533466',
  VaultBusinessLogic__CallerNotLenderSigner: '0xd2b52a69',
  VaultBusinessLogic__LendIntentAlreadyMatched: '0xdd167644',
  VaultBusinessLogic__AssetMismatch: '0xf2775488',
  VaultBusinessLogic__InsufficientReservedSum: '0x45bbee8a',
  VaultBusinessLogic__InsufficientCollateral: '0x3ffde9ad',
  VaultBusinessLogic__BlocksOnlyTermOutOfRange: '0xc4f6c9e6',
  VaultBusinessLogic__BlocksOnlyRateTooLow: '0xaaf1c573',
  SettlementManager__OnlyVaultCore: '0x4bfaf454',
  SettlementManager__InvalidOrderId: '0xb18567bd',
  SettlementManager__NotLiquidatable: '0xdac66f88',
  SettlementManager__BorrowerCannotSelfLiquidate: '0x6a4e8f8a',
  SettlementManager__NoCollateral: '0x66e24701',
  SettlementManager__OrderMismatch: '0xe96a3c5b',
  SettlementManager__DebtNotCleared: '0x6df1bfca',
  SettlementManager__RepayPullMismatch: '0x02288c66',
  SettlementManager__InvalidImplementation: '0x259df050',
  BlocksOnlyCoordinator__OnlyVaultBusinessLogic: '0x34399ce0',
  BlocksOnlyCoordinator__OnlyBorrower: '0xf8190fbb',
  BlocksOnlyCoordinator__InvalidOrderId: '0x5545768f',
  BlocksOnlyCoordinator__OrderNotActive: '0xbfa24650',
  BlocksOnlyCoordinator__InvalidTermBlocks: '0xa306ce98',
  BlocksOnlyCoordinator__InvalidRateBps: '0x2da6023a',
  BlocksOnlyCoordinator__InvalidLender: '0x01c9c4c0',
  BlocksOnlyCoordinator__NotMatured: '0xed7e74c1',
  BlocksOnlyCoordinator__NoCollateral: '0xcf7afaff',
} as const;

export const CONTRACT_ERROR_NAME_BY_SELECTOR = {
  '0xd92e233d': 'ZeroAddress',
  '0x07183e3c': 'NotAContract',
  '0x43ad20fc': 'AmountIsZero',
  '0x48472343': 'AssetNotAllowed',
  '0x48f5c3ed': 'InvalidCaller',
  '0x0d8a86a6': 'ArrayLengthMismatch',
  '0x50042902': 'SettlementIntentLib__AlreadyMatched',
  '0xceb96a30': 'SettlementIntentLib__IntentExpired',
  '0x2d077363': 'SettlementIntentLib__InvalidSignature',
  '0x40533466': 'VaultBusinessLogic__InvalidLendIntentHash',
  '0xd2b52a69': 'VaultBusinessLogic__CallerNotLenderSigner',
  '0xdd167644': 'VaultBusinessLogic__LendIntentAlreadyMatched',
  '0xf2775488': 'VaultBusinessLogic__AssetMismatch',
  '0x45bbee8a': 'VaultBusinessLogic__InsufficientReservedSum',
  '0x3ffde9ad': 'VaultBusinessLogic__InsufficientCollateral',
  '0xc4f6c9e6': 'VaultBusinessLogic__BlocksOnlyTermOutOfRange',
  '0xaaf1c573': 'VaultBusinessLogic__BlocksOnlyRateTooLow',
  '0x4bfaf454': 'SettlementManager__OnlyVaultCore',
  '0xb18567bd': 'SettlementManager__InvalidOrderId',
  '0xdac66f88': 'SettlementManager__NotLiquidatable',
  '0x6a4e8f8a': 'SettlementManager__BorrowerCannotSelfLiquidate',
  '0x66e24701': 'SettlementManager__NoCollateral',
  '0xe96a3c5b': 'SettlementManager__OrderMismatch',
  '0x6df1bfca': 'SettlementManager__DebtNotCleared',
  '0x02288c66': 'SettlementManager__RepayPullMismatch',
  '0x259df050': 'SettlementManager__InvalidImplementation',
  '0x34399ce0': 'BlocksOnlyCoordinator__OnlyVaultBusinessLogic',
  '0xf8190fbb': 'BlocksOnlyCoordinator__OnlyBorrower',
  '0x5545768f': 'BlocksOnlyCoordinator__InvalidOrderId',
  '0xbfa24650': 'BlocksOnlyCoordinator__OrderNotActive',
  '0xa306ce98': 'BlocksOnlyCoordinator__InvalidTermBlocks',
  '0x2da6023a': 'BlocksOnlyCoordinator__InvalidRateBps',
  '0x01c9c4c0': 'BlocksOnlyCoordinator__InvalidLender',
  '0xed7e74c1': 'BlocksOnlyCoordinator__NotMatured',
  '0xcf7afaff': 'BlocksOnlyCoordinator__NoCollateral',
} as const;

export type ContractErrorDefinition = (typeof CONTRACT_ERROR_DEFINITIONS)[number];
export type ContractErrorName = keyof typeof CONTRACT_ERROR_MESSAGES;
