/**
 * ModuleKeys - 模块键常量库（动态计算版）
 * ModuleKeys - Module Key Constants Library (Dynamic Hash Computation)
 *
 * 此文件由 frontend-config/scripts/generateModuleKeys.ts 自动生成
 * This file is automatically generated by frontend-config/scripts/generateModuleKeys.ts
 *
 * ⚠️ 请勿手动修改，如需更新请运行: pnpm generate:module-keys
 * ⚠️ Do not modify manually, run: pnpm generate:module-keys to update
 *
 * SSOT: contracts/src/constants/ModuleKeys.sol
 * 生成时间 / Generated at: 2026-04-17T13:21:48.530Z
 *
 * 设计原则:
 *   - 零硬编码哈希：仅保存 keccak256 的输入字符串
 *   - 运行时通过 ethers.keccak256(ethers.toUtf8Bytes(input)) 计算哈希
 *   - 与 Solidity 中 keccak256("MODULE_NAME") 完全一致
 */

import { keccak256, toUtf8Bytes } from 'ethers';

// ============ SSOT 映射：常量名 → keccak256 输入字符串 ============
// 来源: contracts/src/constants/ModuleKeys.sol
// 每个键的哈希值 = keccak256(toUtf8Bytes(value))
export const MODULE_KEY_INPUTS = {
  /** CollateralManager module key. Used by Registry to store the CollateralManager contract address. Hash: keccak256("COLLATERAL_MANAGER") */
  KEY_CM: 'COLLATERAL_MANAGER',
  /** Lending engine (ledger) module key (VaultLendingEngine / ILendingEngineBasic legacy umbrella). Used by Registry to store the lending engine contract address. Hash: keccak256("LENDING_ENGINE") */
  KEY_LE: 'LENDING_ENGINE',
  /** Vault lending engine module key. Used by Registry to store the VaultLendingEngine contract address. Hash: keccak256("VAULT_LENDING_ENGINE") */
  KEY_VAULT_LENDING_ENGINE: 'VAULT_LENDING_ENGINE',
  /** Order engine module key (core/LendingEngine / IOrderEngine). Used by Registry to store the order engine contract address. Hash: keccak256("ORDER_ENGINE") */
  KEY_ORDER_ENGINE: 'ORDER_ENGINE',
  /** Canonical multi-product order-state SSOT module key. Used by Registry to store the OrderStateStoreV2 contract address. Hash: keccak256("ORDER_STATE_STORE") */
  KEY_ORDER_STATE_STORE: 'ORDER_STATE_STORE',
  /** Deprecated: health factor calculator module key. Replaced by LiquidationRiskManager / HealthView. Preserved as a placeholder to avoid breaking legacy data/scripts; new code must not use it. Hash: keccak256("HEALTH_FACTOR_CALCULATOR") */
  KEY_HF_CALC: 'HEALTH_FACTOR_CALCULATOR',
  /** Vault statistics module key. Used by Registry to store the VaultStatistics (or StatisticsView) contract address. Hash: keccak256("VAULT_STATISTICS") */
  KEY_STATS: 'VAULT_STATISTICS',
  /** Statistics push orchestrator module key (strict B+). Used by Registry to store the StatisticsPushManager (a.k.a. ViewPushOrchestrator) contract address. Hash: keccak256("STATISTICS_PUSH_MANAGER") */
  KEY_STATS_PUSH_MANAGER: 'STATISTICS_PUSH_MANAGER',
  /** Loan flow view module key (protocol loan flow metrics, shared valuation-unit SSOT). Used by Registry to store the LoanFlowView contract address. Hash: keccak256("LOAN_FLOW_VIEW") */
  KEY_LOAN_FLOW_VIEW: 'LOAN_FLOW_VIEW',
  /** Loan flow push orchestrator module key (strict B+). Used by Registry to store the LoanFlowPushManager contract address. Hash: keccak256("LOAN_FLOW_PUSH_MANAGER") */
  KEY_LOAN_FLOW_PUSH_MANAGER: 'LOAN_FLOW_PUSH_MANAGER',
  /** Degradation core monitoring module identifier Hash: keccak256("DEGRADATION_CORE") */
  KEY_DEGRADATION_CORE: 'DEGRADATION_CORE',
  /** Degradation monitor (keeper) module identifier Hash: keccak256("DEGRADATION_MONITOR") */
  KEY_DEGRADATION_MONITOR: 'DEGRADATION_MONITOR',
  /** Degradation storage module identifier Hash: keccak256("DEGRADATION_STORAGE") */
  KEY_DEGRADATION_STORAGE: 'DEGRADATION_STORAGE',
  /** Module health view module identifier Hash: keccak256("MODULE_HEALTH_VIEW") */
  KEY_MODULE_HEALTH_VIEW: 'MODULE_HEALTH_VIEW',
  /** Batch view module identifier Hash: keccak256("BATCH_VIEW") */
  KEY_BATCH_VIEW: 'BATCH_VIEW',
  /** Vault configuration module key. Used by Registry to store the VaultConfig contract address. Hash: keccak256("VAULT_CONFIG") */
  KEY_VAULT_CONFIG: 'VAULT_CONFIG',
  /** Vault core module key. Used by Registry to store the VaultCore contract address. Hash: keccak256("VAULT_CORE") */
  KEY_VAULT_CORE: 'VAULT_CORE',
  /** Fee router module key. Used by Registry to store the FeeRouter contract address. Hash: keccak256("FEE_ROUTER") */
  KEY_FR: 'FEE_ROUTER',
  /** Fee router view module key. Used by Registry to store the FeeRouterView contract address. Hash: keccak256("FEE_ROUTER_VIEW") */
  KEY_FRV: 'FEE_ROUTER_VIEW',
  /** Reward manager module key. Used by Registry to store the RewardManager contract address. Hash: keccak256("REWARD_MANAGER") */
  KEY_RM: 'REWARD_MANAGER',
  /** Reward manager core module key. Used by Registry to store the RewardManagerCore contract address. Hash: keccak256("REWARD_MANAGER_CORE") */
  KEY_REWARD_MANAGER_CORE: 'REWARD_MANAGER_CORE',
  /** Reward accrual manager module key. Used by Registry to store the RewardAccrualManager contract address. Hash: keccak256("REWARD_ACCRUAL_MANAGER") */
  KEY_REWARD_ACCRUAL_MANAGER: 'REWARD_ACCRUAL_MANAGER',
  /** Reward configuration module key. Used by Registry to store the RewardConfig contract address. Hash: keccak256("REWARD_CONFIG") */
  KEY_REWARD_CONFIG: 'REWARD_CONFIG',
  /** Reward earn-configuration submodule key. Used by Registry to store the EarnConfig contract address. Hash: keccak256("REWARD_EARN_CONFIG") */
  KEY_REWARD_EARN_CONFIG: 'REWARD_EARN_CONFIG',
  /** Easy emission config module key. Used by Registry to store the EasyEmissionConfig contract address. Hash: keccak256("EASY_EMISSION_CONFIG") */
  KEY_EASY_EMISSION_CONFIG: 'EASY_EMISSION_CONFIG',
  /** Easy emission controller module key. Used by Registry to store the EasyEmissionController contract address. Hash: keccak256("EASY_EMISSION_CONTROLLER") */
  KEY_EASY_EMISSION_CONTROLLER: 'EASY_EMISSION_CONTROLLER',
  /** Easy consumption module key. Used by Registry to store the EasyConsumption contract address. Hash: keccak256("EASY_CONSUMPTION") */
  KEY_EASY_CONSUMPTION: 'EASY_CONSUMPTION',
  /** Easy recycle distributor module key. Used by Registry to store the EasyRecycleDistributor contract address. Hash: keccak256("EASY_RECYCLE_DISTRIBUTOR") */
  KEY_EASY_RECYCLE_DISTRIBUTOR: 'EASY_RECYCLE_DISTRIBUTOR',
  /** Deprecated: valuation oracle adapter module key. Replaced by KEY_PRICE_ORACLE; preserved for backward compatibility only. New code must not use it. Hash: keccak256("VALUATION_ORACLE") */
  KEY_VALUATION_ORACLE: 'VALUATION_ORACLE',
  /** ValuationOracleView module key (canonical price view facade). Used by Registry to store the ValuationOracleView contract address. Hash: keccak256("VALUATION_ORACLE_VIEW") */
  KEY_VALUATION_ORACLE_VIEW: 'VALUATION_ORACLE_VIEW',
  /** Guarantee fund manager module key. Used by Registry to store the GuaranteeFundManager contract address. Hash: keccak256("GUARANTEE_FUND_MANAGER") */
  KEY_GUARANTEE_FUND: 'GUARANTEE_FUND_MANAGER',
  /** Early repayment guarantee manager module key. Used by Registry to store the EarlyRepaymentGuaranteeManager contract address. Hash: keccak256("EARLY_REPAYMENT_GUARANTEE_MANAGER") */
  KEY_EARLY_REPAYMENT_GUARANTEE: 'EARLY_REPAYMENT_GUARANTEE_MANAGER',
  /** Keeper registry module key. Used by Registry to store the KeeperRegistry contract address. Hash: keccak256("KEEPER_REGISTRY") */
  KEY_KEEPER_REGISTRY: 'KEEPER_REGISTRY',
  /** Whitelist registry module key. Used by Registry to store the WhitelistRegistry contract address. Hash: keccak256("WHITELIST_REGISTRY") */
  KEY_WHITELIST_REGISTRY: 'WHITELIST_REGISTRY',
  /** Access control manager module key. Used by Registry to store the AccessControlManager contract address. Hash: keccak256("ACCESS_CONTROL_MANAGER") */
  KEY_ACCESS_CONTROL: 'ACCESS_CONTROL_MANAGER',
  /** Access controller module key (enhanced). Used by Registry to store the AccessController contract address. Hash: keccak256("ACCESS_CONTROLLER") */
  KEY_ACCESS_CONTROLLER: 'ACCESS_CONTROLLER',
  /** Asset whitelist module key. Used by Registry to store the AssetWhitelist contract address. Hash: keccak256("ASSET_WHITELIST") */
  KEY_ASSET_WHITELIST: 'ASSET_WHITELIST',
  /** Authority whitelist module key. Used by Registry to store the AuthorityWhitelist contract address. Hash: keccak256("AUTHORITY_WHITELIST") */
  KEY_AUTHORITY_WHITELIST: 'AUTHORITY_WHITELIST',
  /** Settlement manager (unified settlement/liquidation write entry) module key. Used by Registry to store the SettlementManager contract address. Hash: keccak256("SETTLEMENT_MANAGER") */
  KEY_SETTLEMENT_MANAGER: 'SETTLEMENT_MANAGER',
  /** Lender pool vault module key (recommended on-chain liquidity pool location). Used by Registry to store the LenderPoolVault contract address. Hash: keccak256("LENDER_POOL_VAULT") */
  KEY_LENDER_POOL_VAULT: 'LENDER_POOL_VAULT',
  /** Liquidation manager module key. Used by Registry to store the LiquidationManager contract address. Hash: keccak256("LIQUIDATION_MANAGER") */
  KEY_LIQUIDATION_MANAGER: 'LIQUIDATION_MANAGER',
  /** Liquidation risk manager module key. Used by Registry to store the LiquidationRiskManager contract address. Hash: keccak256("LIQUIDATION_RISK_MANAGER") */
  KEY_LIQUIDATION_RISK_MANAGER: 'LIQUIDATION_RISK_MANAGER',
  /** Liquidation calculator module key. Used by Registry to store the LiquidationCalculator contract address. Hash: keccak256("LIQUIDATION_CALCULATOR") */
  KEY_LIQUIDATION_CALCULATOR: 'LIQUIDATION_CALCULATOR',
  /** Liquidation config manager module key. Used by Registry to store the LiquidationConfigManager contract address. Hash: keccak256("LIQUIDATION_CONFIG_MANAGER") */
  KEY_LIQUIDATION_CONFIG_MANAGER: 'LIQUIDATION_CONFIG_MANAGER',
  /** Liquidation orchestrator module key. Used by Registry to store the LiquidationOrchestrator contract address. Hash: keccak256("LIQUIDATION_ORCHESTRATOR") */
  KEY_LIQUIDATION_ORCHESTRATOR: 'LIQUIDATION_ORCHESTRATOR',
  /** Degradation manager module key. Used by Registry to store the DegradationManager contract address. Hash: keccak256("DEGRADATION_MANAGER") */
  KEY_DEGRADATION_MANAGER: 'DEGRADATION_MANAGER',
  /** Dynamic module registry module key. Used by Registry to store the RegistryDynamicModuleKey contract address. Hash: keccak256("DYNAMIC_MODULE_REGISTRY") */
  KEY_DYNAMIC_MODULE_REGISTRY: 'DYNAMIC_MODULE_REGISTRY',
  /** Cache maintenance manager module key (governance ops: batch refresh module caches). Used by Registry to store the CacheMaintenanceManager contract address. Hash: keccak256("CACHE_MAINTENANCE_MANAGER") */
  KEY_CACHE_MAINTENANCE_MANAGER: 'CACHE_MAINTENANCE_MANAGER',
  /** Cross-chain governance module key. Used by Registry to store the CrossChainGovernance contract address. Hash: keccak256("CROSS_CHAIN_GOVERNANCE") */
  KEY_CROSS_CHAIN_GOV: 'CROSS_CHAIN_GOVERNANCE',
  /** Governance role module key. Used by Registry to store the GovernanceRole contract address. Hash: keccak256("GOVERNANCE_ROLE") */
  KEY_GOVERNANCE_ROLE: 'GOVERNANCE_ROLE',
  /** Governance escrow module key (DEPRECATED in SSOT "one-token-two-uses" mode). Kept for backward compatibility. SSOT target-state uses EasyToken directly as IVotes token. Hash: keccak256("GOVERNANCE_ESCROW") */
  KEY_GOVERNANCE_ESCROW: 'GOVERNANCE_ESCROW',
  /** Governance gate (SSOT) module key. Used by Registry to store the GovernanceGate contract address. Hash: keccak256("GOVERNANCE_GATE") */
  KEY_GOVERNANCE_GATE: 'GOVERNANCE_GATE',
  /** Feature registry (SSOT) module key. Used by Registry to store the FeatureRegistry contract address. Hash: keccak256("FEATURE_REGISTRY") */
  KEY_FEATURE_REGISTRY: 'FEATURE_REGISTRY',
  /** Governance guardian (foundation veto) address key. Stored as a module-address entry in Registry for SSOT + migration. Hash: keccak256("GOVERNANCE_GUARDIAN") */
  KEY_GOVERNANCE_GUARDIAN: 'GOVERNANCE_GUARDIAN',
  /** Registry module key. Used by Registry to store the Registry contract address. Hash: keccak256("REGISTRY") */
  KEY_REGISTRY: 'REGISTRY',
  /** Loan NFT module key. Used by Registry to store the LoanNFT contract address. Hash: keccak256("LOAN_NFT") */
  KEY_LOAN_NFT: 'LOAN_NFT',
  /** Easy token module key. Used by Registry to store the EasyToken contract address. Hash: keccak256("EASY_TOKEN") */
  KEY_EASY_TOKEN: 'EASY_TOKEN',
  /** Easy staking module key. Used by Registry to store the EasyStaking contract address. Hash: keccak256("EASY_STAKING") */
  KEY_EASY_STAKING: 'EASY_STAKING',
  /** AI credits vault module key. Used by Registry to store the AICreditsVault contract address. Hash: keccak256("AI_CREDITS_VAULT") */
  KEY_AI_CREDITS_VAULT: 'AI_CREDITS_VAULT',
  /** RWA token module key. Used by Registry to store the RWAToken contract address. Hash: keccak256("RWA_TOKEN") */
  KEY_RWA_TOKEN: 'RWA_TOKEN',
  /** Token utilities module key. Used by Registry to store the TokenUtils contract address. Hash: keccak256("TOKEN_UTILS") */
  KEY_TOKEN_UTILS: 'TOKEN_UTILS',
  /** Revert decoder module key. Used by Registry to store the RevertDecoder contract address. Hash: keccak256("REVERT_DECODER") */
  KEY_REVERT_DECODER: 'REVERT_DECODER',
  /** Vault utilities module key. Used by Registry to store the VaultUtils contract address. Hash: keccak256("VAULT_UTILS") */
  KEY_VAULT_UTILS: 'VAULT_UTILS',
  /** Price oracle module key. Used by Registry to store the PriceOracle contract address. Hash: keccak256("PRICE_ORACLE") */
  KEY_PRICE_ORACLE: 'PRICE_ORACLE',
  /** Price updater module key. Used by Registry to store the PriceUpdater contract address. Preserves the legacy CoinGecko hash input for onchain compatibility. Hash: keccak256("COINGECKO_PRICE_UPDATER") */
  KEY_PRICE_UPDATER: 'COINGECKO_PRICE_UPDATER',
  /** Price updater view module key. Used by Registry to store the PriceUpdaterView contract address. Preserves the legacy CoinGecko hash input for onchain compatibility. Hash: keccak256("COINGECKO_PRICE_UPDATER_VIEW") */
  KEY_PRICE_UPDATER_VIEW: 'COINGECKO_PRICE_UPDATER_VIEW',
  /** Settlement token module key. Used by Registry to store the SettlementToken contract address. Hash: keccak256("SETTLEMENT_TOKEN") */
  KEY_SETTLEMENT_TOKEN: 'SETTLEMENT_TOKEN',
  /** RWA auto leveraged strategy module key. Used by Registry to store the RWAAutoLeveragedStrategy contract address. Hash: keccak256("RWA_AUTO_LEVERAGED_STRATEGY") */
  KEY_RWA_STRATEGY: 'RWA_AUTO_LEVERAGED_STRATEGY',
  /** Vault business logic module key. Used by Registry to store the VaultBusinessLogic contract address. Hash: keccak256("VAULT_BUSINESS_LOGIC") */
  KEY_VAULT_BUSINESS_LOGIC: 'VAULT_BUSINESS_LOGIC',
  /** Registry key for the standalone blocks-only coordinator module. Used to resolve the BlocksOnlyCoordinator contract that owns blocks-only order creation, Hash: keccak256("BLOCKS_ONLY_COORDINATOR") */
  KEY_BLOCKS_ONLY_COORDINATOR: 'BLOCKS_ONLY_COORDINATOR',
  /** Registry key for the dedicated blocks-only view module. Used to resolve the BlocksOnlyView contract that exposes permissioned order and runtime read helpers. Hash: keccak256("BLOCKS_ONLY_VIEW") */
  KEY_BLOCKS_ONLY_VIEW: 'BLOCKS_ONLY_VIEW',
  /** HealthView module key. Used by Registry to store the HealthView contract address. Hash: keccak256("HEALTH_VIEW") */
  KEY_HEALTH_VIEW: 'HEALTH_VIEW',
  /** RiskView module key (legacy). Used by Registry to store the RiskView contract address. Hash: keccak256("RISK_VIEW") */
  KEY_RISK_VIEW: 'RISK_VIEW',
  /** SystemRiskView module key. Used by Registry to store the SystemRiskView contract address. Hash: keccak256("SYSTEM_RISK_VIEW") */
  KEY_SYSTEM_RISK_VIEW: 'SYSTEM_RISK_VIEW',
  /** SystemView module key. Used by Registry to store the SystemView contract address. Hash: keccak256("SYSTEM_VIEW") */
  KEY_SYSTEM_VIEW: 'SYSTEM_VIEW',
  /** UserViewFacade module key. Used by Registry to store the UserViewFacade contract address. Hash: keccak256("USER_VIEW") */
  KEY_USER_VIEW: 'USER_VIEW',
  /** PositionView module key. Used by Registry to store the PositionView contract address. Hash: keccak256("POSITION_VIEW") */
  KEY_POSITION_VIEW: 'POSITION_VIEW',
  /** DashboardView module key. Used by Registry to store the DashboardView contract address. Hash: keccak256("DASHBOARD_VIEW") */
  KEY_DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  /** PreviewView module key. Used by Registry to store the PreviewView contract address. Hash: keccak256("PREVIEW_VIEW") */
  KEY_PREVIEW_VIEW: 'PREVIEW_VIEW',
  /** LiquidationEventsView module key. Used by Registry to store the LiquidationEventsView contract address. Hash: keccak256("LIQUIDATION_VIEW") */
  KEY_LIQUIDATION_VIEW: 'LIQUIDATION_VIEW',
  /** RewardView module key. Used by Registry to store the RewardView contract address. Hash: keccak256("REWARD_VIEW") */
  KEY_REWARD_VIEW: 'REWARD_VIEW',
  /** View cache module key. Used by Registry to store the ViewCache contract address. Hash: keccak256("VIEW_CACHE") */
  KEY_VIEW_CACHE: 'VIEW_CACHE',
  /** RegistryView module key. Read-only registry view for enumeration / reverse-lookup / pagination queries. Hash: keccak256("REGISTRY_VIEW") */
  KEY_REGISTRY_VIEW: 'REGISTRY_VIEW',
  /** SystemHealthView module key. Read-only system health / degradation view. Hash: keccak256("SYSTEM_HEALTH_VIEW") */
  KEY_SYSTEM_HEALTH_VIEW: 'SYSTEM_HEALTH_VIEW',
  /** Liquidation payout manager module key. Used by Registry to store the LiquidationPayoutManager contract address. Hash: keccak256("LIQUIDATION_PAYOUT_MANAGER") */
  KEY_LIQUIDATION_PAYOUT_MANAGER: 'LIQUIDATION_PAYOUT_MANAGER',
  /** Event history manager module key. Used by Registry to store the EventHistoryManager contract address. Hash: keccak256("EVENT_HISTORY_MANAGER") */
  KEY_EVENT_HISTORY_MANAGER: 'EVENT_HISTORY_MANAGER',
  /** Reward manager V1 module key (example). Used by Registry to store the RewardManager V1 contract address. Hash: keccak256("REWARD_MANAGER_V1") */
  KEY_REWARD_MANAGER_V1: 'REWARD_MANAGER_V1',
} as const;

// ============ 类型定义 ============

/**
 * 模块键名称类型
 * Module key name type
 */
export type ModuleKeyName = keyof typeof MODULE_KEY_INPUTS;

/**
 * 模块键字符串数组
 * Module key strings array
 */
export const MODULE_KEY_STRINGS = [
  'KEY_CM',
  'KEY_LE',
  'KEY_VAULT_LENDING_ENGINE',
  'KEY_ORDER_ENGINE',
  'KEY_ORDER_STATE_STORE',
  'KEY_HF_CALC',
  'KEY_STATS',
  'KEY_STATS_PUSH_MANAGER',
  'KEY_LOAN_FLOW_VIEW',
  'KEY_LOAN_FLOW_PUSH_MANAGER',
  'KEY_DEGRADATION_CORE',
  'KEY_DEGRADATION_MONITOR',
  'KEY_DEGRADATION_STORAGE',
  'KEY_MODULE_HEALTH_VIEW',
  'KEY_BATCH_VIEW',
  'KEY_VAULT_CONFIG',
  'KEY_VAULT_CORE',
  'KEY_FR',
  'KEY_FRV',
  'KEY_RM',
  'KEY_REWARD_MANAGER_CORE',
  'KEY_REWARD_ACCRUAL_MANAGER',
  'KEY_REWARD_CONFIG',
  'KEY_REWARD_EARN_CONFIG',
  'KEY_EASY_EMISSION_CONFIG',
  'KEY_EASY_EMISSION_CONTROLLER',
  'KEY_EASY_CONSUMPTION',
  'KEY_EASY_RECYCLE_DISTRIBUTOR',
  'KEY_VALUATION_ORACLE',
  'KEY_VALUATION_ORACLE_VIEW',
  'KEY_GUARANTEE_FUND',
  'KEY_EARLY_REPAYMENT_GUARANTEE',
  'KEY_KEEPER_REGISTRY',
  'KEY_WHITELIST_REGISTRY',
  'KEY_ACCESS_CONTROL',
  'KEY_ACCESS_CONTROLLER',
  'KEY_ASSET_WHITELIST',
  'KEY_AUTHORITY_WHITELIST',
  'KEY_SETTLEMENT_MANAGER',
  'KEY_LENDER_POOL_VAULT',
  'KEY_LIQUIDATION_MANAGER',
  'KEY_LIQUIDATION_RISK_MANAGER',
  'KEY_LIQUIDATION_CALCULATOR',
  'KEY_LIQUIDATION_CONFIG_MANAGER',
  'KEY_LIQUIDATION_ORCHESTRATOR',
  'KEY_DEGRADATION_MANAGER',
  'KEY_DYNAMIC_MODULE_REGISTRY',
  'KEY_CACHE_MAINTENANCE_MANAGER',
  'KEY_CROSS_CHAIN_GOV',
  'KEY_GOVERNANCE_ROLE',
  'KEY_GOVERNANCE_ESCROW',
  'KEY_GOVERNANCE_GATE',
  'KEY_FEATURE_REGISTRY',
  'KEY_GOVERNANCE_GUARDIAN',
  'KEY_REGISTRY',
  'KEY_LOAN_NFT',
  'KEY_EASY_TOKEN',
  'KEY_EASY_STAKING',
  'KEY_AI_CREDITS_VAULT',
  'KEY_RWA_TOKEN',
  'KEY_TOKEN_UTILS',
  'KEY_REVERT_DECODER',
  'KEY_VAULT_UTILS',
  'KEY_PRICE_ORACLE',
  'KEY_PRICE_UPDATER',
  'KEY_PRICE_UPDATER_VIEW',
  'KEY_SETTLEMENT_TOKEN',
  'KEY_RWA_STRATEGY',
  'KEY_VAULT_BUSINESS_LOGIC',
  'KEY_BLOCKS_ONLY_COORDINATOR',
  'KEY_BLOCKS_ONLY_VIEW',
  'KEY_HEALTH_VIEW',
  'KEY_RISK_VIEW',
  'KEY_SYSTEM_RISK_VIEW',
  'KEY_SYSTEM_VIEW',
  'KEY_USER_VIEW',
  'KEY_POSITION_VIEW',
  'KEY_DASHBOARD_VIEW',
  'KEY_PREVIEW_VIEW',
  'KEY_LIQUIDATION_VIEW',
  'KEY_REWARD_VIEW',
  'KEY_VIEW_CACHE',
  'KEY_REGISTRY_VIEW',
  'KEY_SYSTEM_HEALTH_VIEW',
  'KEY_LIQUIDATION_PAYOUT_MANAGER',
  'KEY_EVENT_HISTORY_MANAGER',
  'KEY_REWARD_MANAGER_V1',
] as const;

/**
 * 模块键类型（兼容旧版）
 * Module key type (backward compatible)
 */
export type ModuleKey = typeof MODULE_KEY_STRINGS[number];

// ============ 动态哈希计算 ============

/**
 * 从输入字符串映射计算所有模块键的 bytes32 哈希
 * Compute all module key bytes32 hashes from input string mapping
 *
 * 等价于 Solidity: keccak256("MODULE_NAME")
 */
function computeModuleKeys(): Record<ModuleKeyName, string> {
  const result = {} as Record<ModuleKeyName, string>;
  for (const [key, input] of Object.entries(MODULE_KEY_INPUTS)) {
    result[key as ModuleKeyName] = keccak256(toUtf8Bytes(input));
  }
  return result;
}

/**
 * 模块键常量映射（动态计算的 keccak256 哈希）
 * Module key constants mapping (dynamically computed keccak256 hashes)
 *
 * 使用方式与硬编码版完全相同:
 *   ModuleKeys.KEY_VAULT_CORE  // → '0xe015...'
 */
export const ModuleKeys: Readonly<Record<ModuleKeyName, string>> = computeModuleKeys();

// ============ 工具函数 ============

/**
 * 验证模块键名称是否有效
 * Validate if module key name is valid
 * @param key 模块键名称 / Module key name
 * @returns 是否有效 / Is valid
 */
export function isValidModuleKey(key: string): key is ModuleKey {
  return MODULE_KEY_STRINGS.includes(key as ModuleKey);
}

/**
 * 获取模块键的 bytes32 哈希值
 * Get bytes32 hash value of module key
 * @param key 模块键名称 / Module key name
 * @returns 哈希值 / Hash value
 */
export function getModuleKeyHash(key: ModuleKey): string {
  return ModuleKeys[key];
}

/**
 * 获取模块键的 keccak256 输入字符串
 * Get keccak256 input string of module key
 * @param key 模块键名称 / Module key name
 * @returns 输入字符串（如 'COLLATERAL_MANAGER'）/ Input string
 */
export function getModuleKeyInput(key: ModuleKey): string {
  return MODULE_KEY_INPUTS[key];
}

/**
 * 从 bytes32 哈希值反查模块键名称
 * Get module key name from bytes32 hash value
 * @param hash 哈希值 / Hash value
 * @returns 模块键名称或 null / Module key name or null
 */
export function getModuleKeyFromHash(hash: string): ModuleKey | null {
  const normalized = hash.toLowerCase();
  for (const [key, value] of Object.entries(ModuleKeys)) {
    if (value.toLowerCase() === normalized) {
      return key as ModuleKey;
    }
  }
  return null;
}

/**
 * 获取所有模块键名称
 * Get all module key names
 * @returns 所有模块键名称数组 / All module key names array
 */
export function getAllModuleKeys(): ModuleKey[] {
  return [...MODULE_KEY_STRINGS];
}

/**
 * 获取模块键总数
 * Get total number of module keys
 * @returns 模块键总数 / Total number of module keys
 */
export function getModuleKeyCount(): number {
  return MODULE_KEY_STRINGS.length;
}

export default ModuleKeys;
