#!/usr/bin/env ts-node
/**
 * generateModuleKeys.ts
 *
 * 从 Solidity 源码 ModuleKeys.sol 中解析所有 `bytes32 internal constant KEY_XXX = keccak256("YYY")`，
 * 自动生成 frontend-config/moduleKeys.ts 兼容产物。
 * 当前正式生成链见 docs/Contract-Artifact-Generation-Guide.md。
 *
 * 用法:
 *   npx ts-node frontend-config/scripts/generateModuleKeys.ts
 *   # 或
 *   pnpm generate:module-keys
 *
 * 设计原则:
 *   - 零硬编码哈希：moduleKeys.ts 只保存 KEY 名 → keccak256 输入字符串 的映射
 *   - SSOT: 合约源码 ModuleKeys.sol 是唯一真相源
 *   - ABI 文件只读，绝不写入
 */

import * as fs from 'fs';
import * as path from 'path';

// ============ 配置 ============
// 合约源码路径（可通过环境变量覆盖）
const SOLIDITY_SOURCE = process.env.MODULE_KEYS_SOL_PATH
  || path.resolve(__dirname, '../../src/constants/ModuleKeys.sol');

const OUTPUT_PATH = path.resolve(__dirname, '../moduleKeys.ts');

// ============ 解析逻辑 ============

interface ModuleKeyEntry {
  /** 常量名，如 KEY_CM */
  constantName: string;
  /** keccak256 输入字符串，如 COLLATERAL_MANAGER */
  hashInput: string;
  /** 原始注释中的 @deprecated 标记 */
  deprecated: boolean;
  /** 注释说明 */
  comment: string;
}

/**
 * 从 ModuleKeys.sol 源文件中提取所有 bytes32 常量定义
 */
function parseModuleKeysSol(solPath: string): ModuleKeyEntry[] {
  if (!fs.existsSync(solPath)) {
    throw new Error(`ModuleKeys.sol 未找到: ${solPath}`);
  }

  const source = fs.readFileSync(solPath, 'utf-8');
  const lines = source.split('\n');
  const entries: ModuleKeyEntry[] = [];

  // 匹配: bytes32 internal constant KEY_XXX = keccak256("YYY");
  const constantRegex = /bytes32\s+internal\s+constant\s+(KEY_\w+)\s*=\s*keccak256\("([^"]+)"\)\s*;/;

  let pendingComment = '';
  let pendingDeprecated = false;

  for (const line of lines) {
    const trimmed = line.trim();

    // 收集注释
    if (trimmed.startsWith('///') || trimmed.startsWith('*')) {
      const commentText = trimmed.replace(/^\/\/\/\s*/, '').replace(/^\*\s*/, '');
      if (commentText.toLowerCase().includes('@deprecated')) {
        pendingDeprecated = true;
      }
      if (commentText.startsWith('@notice') || commentText.startsWith('@dev')) {
        pendingComment += commentText.replace(/^@(notice|dev)\s*/, '') + ' ';
      }
      continue;
    }

    const match = trimmed.match(constantRegex);
    if (match) {
      entries.push({
        constantName: match[1],
        hashInput: match[2],
        deprecated: pendingDeprecated,
        comment: pendingComment.trim(),
      });
      pendingComment = '';
      pendingDeprecated = false;
    } else if (!trimmed.startsWith('//')) {
      // 非注释非常量行，重置注释缓冲
      if (trimmed.length > 0 && !trimmed.startsWith('//')) {
        pendingComment = '';
        pendingDeprecated = false;
      }
    }
  }

  return entries;
}

/**
 * 生成 moduleKeys.ts 文件内容
 */
function generateModuleKeysTS(entries: ModuleKeyEntry[]): string {
  const timestamp = new Date().toISOString();

  // 构建 MODULE_KEY_INPUTS 对象
  const inputEntries = entries.map(e => {
    const deprecatedTag = e.deprecated ? '  /** @deprecated */' : '';
    const comment = e.comment ? `  /** ${e.comment} */` : '';
    const annotation = deprecatedTag || comment;
    if (annotation) {
      return `${annotation}\n  ${e.constantName}: '${e.hashInput}',`;
    }
    return `  ${e.constantName}: '${e.hashInput}',`;
  });

  const keyStrings = entries.map(e => `  '${e.constantName}',`);

  return `/**
 * ModuleKeys - 模块键常量库（动态计算版）
 * ModuleKeys - Module Key Constants Library (Dynamic Hash Computation)
 *
 * 此文件由 frontend-config/scripts/generateModuleKeys.ts 自动生成
 * This file is automatically generated by frontend-config/scripts/generateModuleKeys.ts
 *
 * ⚠️ 请勿手动修改，如需更新请运行: pnpm generate:module-keys
 * ⚠️ Do not modify manually, run: pnpm generate:module-keys to update
 *
 * SSOT: contracts/src/constants/ModuleKeys.sol
 * 生成时间 / Generated at: ${timestamp}
 *
 * 设计原则:
 *   - 零硬编码哈希：仅保存 keccak256 的输入字符串
 *   - 运行时通过 ethers.keccak256(ethers.toUtf8Bytes(input)) 计算哈希
 *   - 与 Solidity 中 keccak256("MODULE_NAME") 完全一致
 */

import { keccak256, toUtf8Bytes } from 'ethers';

// ============ SSOT 映射：常量名 → keccak256 输入字符串 ============
// 来源: contracts/src/constants/ModuleKeys.sol
// 每个键的哈希值 = keccak256(toUtf8Bytes(value))
export const MODULE_KEY_INPUTS = {
${inputEntries.join('\n')}
} as const;

// ============ 类型定义 ============

/**
 * 模块键名称类型
 * Module key name type
 */
export type ModuleKeyName = keyof typeof MODULE_KEY_INPUTS;

/**
 * 模块键字符串数组
 * Module key strings array
 */
export const MODULE_KEY_STRINGS = [
${keyStrings.join('\n')}
] as const;

/**
 * 模块键类型（兼容旧版）
 * Module key type (backward compatible)
 */
export type ModuleKey = typeof MODULE_KEY_STRINGS[number];

// ============ 动态哈希计算 ============

/**
 * 从输入字符串映射计算所有模块键的 bytes32 哈希
 * Compute all module key bytes32 hashes from input string mapping
 *
 * 等价于 Solidity: keccak256("MODULE_NAME")
 */
function computeModuleKeys(): Record<ModuleKeyName, string> {
  const result = {} as Record<ModuleKeyName, string>;
  for (const [key, input] of Object.entries(MODULE_KEY_INPUTS)) {
    result[key as ModuleKeyName] = keccak256(toUtf8Bytes(input));
  }
  return result;
}

/**
 * 模块键常量映射（动态计算的 keccak256 哈希）
 * Module key constants mapping (dynamically computed keccak256 hashes)
 *
 * 使用方式与硬编码版完全相同:
 *   ModuleKeys.KEY_VAULT_CORE  // → '0xe015...'
 */
export const ModuleKeys: Readonly<Record<ModuleKeyName, string>> = computeModuleKeys();

// ============ 工具函数 ============

/**
 * 验证模块键名称是否有效
 * Validate if module key name is valid
 * @param key 模块键名称 / Module key name
 * @returns 是否有效 / Is valid
 */
export function isValidModuleKey(key: string): key is ModuleKey {
  return MODULE_KEY_STRINGS.includes(key as ModuleKey);
}

/**
 * 获取模块键的 bytes32 哈希值
 * Get bytes32 hash value of module key
 * @param key 模块键名称 / Module key name
 * @returns 哈希值 / Hash value
 */
export function getModuleKeyHash(key: ModuleKey): string {
  return ModuleKeys[key];
}

/**
 * 获取模块键的 keccak256 输入字符串
 * Get keccak256 input string of module key
 * @param key 模块键名称 / Module key name
 * @returns 输入字符串（如 'COLLATERAL_MANAGER'）/ Input string
 */
export function getModuleKeyInput(key: ModuleKey): string {
  return MODULE_KEY_INPUTS[key];
}

/**
 * 从 bytes32 哈希值反查模块键名称
 * Get module key name from bytes32 hash value
 * @param hash 哈希值 / Hash value
 * @returns 模块键名称或 null / Module key name or null
 */
export function getModuleKeyFromHash(hash: string): ModuleKey | null {
  const normalized = hash.toLowerCase();
  for (const [key, value] of Object.entries(ModuleKeys)) {
    if (value.toLowerCase() === normalized) {
      return key as ModuleKey;
    }
  }
  return null;
}

/**
 * 获取所有模块键名称
 * Get all module key names
 * @returns 所有模块键名称数组 / All module key names array
 */
export function getAllModuleKeys(): ModuleKey[] {
  return [...MODULE_KEY_STRINGS];
}

/**
 * 获取模块键总数
 * Get total number of module keys
 * @returns 模块键总数 / Total number of module keys
 */
export function getModuleKeyCount(): number {
  return MODULE_KEY_STRINGS.length;
}

export default ModuleKeys;
`;
}

// ============ 主程序 ============
function main(): void {
  // 查找 Solidity 源文件
  let solPath = SOLIDITY_SOURCE;
  if (!fs.existsSync(solPath)) {
    console.error('❌ 找不到 ModuleKeys.sol，已尝试:');
    console.error(`   - ${SOLIDITY_SOURCE}`);
    console.error('   设置 MODULE_KEYS_SOL_PATH 环境变量指向正确路径');
    process.exit(1);
  }

  console.log(`📖 读取 Solidity 源码: ${solPath}`);
  const entries = parseModuleKeysSol(solPath);
  console.log(`✅ 解析到 ${entries.length} 个模块键`);

  if (entries.length === 0) {
    console.error('❌ 未解析到任何模块键，请检查 ModuleKeys.sol 格式');
    process.exit(1);
  }

  // 列出所有键
  for (const entry of entries) {
    const tag = entry.deprecated ? ' [DEPRECATED]' : '';
    console.log(`   ${entry.constantName} → keccak256("${entry.hashInput}")${tag}`);
  }

  const output = generateModuleKeysTS(entries);
  fs.writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`\n📝 已生成: ${OUTPUT_PATH}`);
  console.log(`   共 ${entries.length} 个模块键，零硬编码哈希 ✅`);
}

main();
